name: test

on: push

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Show Branch
        run: echo ${{ github.ref_name	}}

      - name: Show ENV Variables
        run: env | sort

      - name: Debug
        run: echo ${{ vars.PROJECT_ENVIRONMENT	}}
