name: test

on:
  pull_request:
  push:
    branches:
      - dev
      - prod

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: ${{ github.event_name == 'pull_request' && 'pull_request' || github.ref_name }}
    steps:
      - name: Show Environment
        run: echo ${{ github.event_name == 'pull_request' && 'pull_request' || github.ref_name }}

      - name: Load Context
        run: |
          echo '${{ toJSON(vars) }}' | jq -r '. | to_entries | .[] | .key + "=" + (.value | @sh)' >> $GITHUB_ENV
          echo '${{ toJSON(secrets) }}' | jq -r '. | to_entries | .[] | .key + "=" + (.value | @sh)' >> $GITHUB_ENV

      - name: Show ENV Variables
        run: env | sort

