name: test

on:
  pull_request:
  push:
    branches:
      - dev
      - prod

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name || 'default' }}
    steps:
      - name: Show Branch
        run: echo ${{ github.ref_name	}}

      - name: Show ENV Variables
        run: env | sort

      - name: Debug
        env:
          VARS_CONTEXT: ${{ toJSON(vars) }}
        run: |
          echo ${{ vars.PROJECT_ENVIRONMENT	}}
          echo '${{ toJSON(vars) }}'

