name: test

env: [{"ANETO": "YEP"}]

on:
  pull_request:
  push:
    branches:
      - dev
      - prod

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: ${{ github.event_name == 'pull_request' && 'pull_request' || github.ref_name }}
    steps:
      - name: Show Environment
        run: echo ${{ github.event_name == 'pull_request' && 'pull_request' || github.ref_name }}

      - name: Show ENV Variables
        run: |
          echo $PROJECT_OWNER

      - name: Debug
        env:
          VARS_CONTEXT: ${{ toJSON(vars) }}
        run: |
          echo ${{ vars.PROJECT_ENVIRONMENT	}}
          echo '${{ toJSON(vars) }}'

