name: test

on: push

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: ${{ GITHUB_REF_NAME	}}
    steps:
      - name: Show Branch
        run: echo ${{ GITHUB_REF_NAME	}}
      - name: Show ENV Variables
        run: env | sort
