name: test

on: push

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: ${{ github.github_ref_name	}}
    steps:
      - name: Show Branch
        run: echo ${{ github.github_ref_name }}
      - name: Show ENV Variables
        run: env | sort
