name: test

on: push

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: ${{ env.GITHUB_REF_NAME	}}
    steps:
      - name: Show Branch
        run: echo ${{ env.GITHUB_REF_NAME }}
      - name: Show ENV Variables
        run: env | sort
